name: Deploy publish folder to GitHub

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en la rama principal

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restaurar Dependencias
        run: dotnet restore

      - name: Compilar Proyecto en Modo Producción
        run: dotnet build WebAppRep.sln --configuration Release

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: publish/wwwroot     
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
