name: Deploy publish folder to GitHub

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en la rama principal

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restaurar Dependencias
        run: dotnet restore
      - name: Publish 
        run: dotnet publish --configuration Release --output build
    # changes the base-tag in index.html from '/' to 'BlazorAppSpendsRegister' to match GitHub Pages repository subdirectory
      - name: Change base-tag 
        run: sed -i 's/<base href="\/" \/>/<base href="\/NetRepository\/" \/>/g' build/wwwroot/index.html
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/wwwroot
